Contact {
    Entity: {
        shape: sql_table

        name: String
        phoneNumber: String
        profilePictureUri: String
    }

    Model: {
        shape: sql_table

        name: String
        phoneNumber: String
        profilePictureUri: Uri?
    }
}